apiVersion: v1
kind: Secret
metadata:
  name: {{ include "magento.fullname" . }}
  labels:
    {{- include "magento.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.password }}
  database-password: {{ .Values.database.password | b64enc | quote }}
  {{- else }}
  database-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- range $i, $user := .Values.adminUsers }}
  {{- if $user.password }}
  admin-password-{{ $i }}: {{ $user.password | b64enc | quote }}
  {{- else }}
  admin-password-{{ $i }}: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.gitSync.credentials.token }}
  git-token: {{ .Values.gitSync.credentials.token | b64enc | quote }}
  {{- end }}
