apiVersion: v1
kind: Secret
metadata:
  name: {{ include "magento.fullname" . }}
  labels:
    {{- include "magento.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.password }}
  database-password: {{ .Values.database.password | b64enc | quote }}
  {{- else }}
  database-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.magento.adminPassword }}
  admin-password: {{ .Values.magento.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.gitSync.credentials.token }}
  git-token: {{ .Values.gitSync.credentials.token | b64enc | quote }}
  {{- end }}
