apiVersion: v2
name: magento
description: Magento 2.4.8 on Kubernetes with git-sync for live plugin development
type: application
version: 0.6.0
appVersion: "2.4.8"
home: https://github.com/brtkwr/magento-helm
sources:
  - https://github.com/brtkwr/magento-helm
maintainers:
  - name: brtkwr
    url: https://github.com/brtkwr
keywords:
  - magento
  - ecommerce
  - kubernetes
  - helm
  - git-sync
